### PR TITLE
handle no @timestamp and fix generateId

### LINKED ISSUE #25: error when using generateId (wrong number of argument)
When i use the generateId option, it raise an exception : 

```
wrong number of arguments calling `initialize` (2 for 0)
/opt/logstash-2.2.0/vendor/bundle/jruby/1.9/gems/logstash-output-mongodb-2.0.3/lib/logstash/outputs/mongodb.rb:54
```

according to doc http://www.rubydoc.info/github/mongodb/bson-ruby/BSON/ObjectId#from_string-class_method
you should replace mongodb.rb line 54 

``` ruby
document["_id"] = BSON::ObjectId.new(nil, event["@timestamp"])
```

by something like 

``` ruby
document["_id"] =  BSON::ObjectId.from_time(event["@timestamp"])
```

with `event["@timestamp"]` a Time object or timestamp

### PR DESCRIPTION
**Pull request by colinsurprenant**
fixes #25 #49

- do not add a `@timestamp` in the MongoDB document if the event does not contain a `@timestamp`
- fix the `generateId` `BSON::ObjectId` generation
- correctly handle close by exiting bulk thread
- added corresponding specs

### CODE REVIEW

File: lib/logstash/outputs/mongodb.rb [hunk 1]
```diff
@@ -46,19 +46,22 @@ class LogStash::Outputs::Mongodb < LogStash::Outputs::Base
...
+    @closed = Concurrent::AtomicBoolean.new(false)
     @documents = {}
-    Thread.new do
+
+    @bulk_thread = Thread.new(@bulk_interval) do |bulk_interval|
       loop do
-        sleep @bulk_interval
+        sleep(bulk_interval)
+
         @@mutex.synchronize do
```
Comment (yaauie) [inline lib/logstash/outputs/mongodb.rb:65]: first time seeing this code, am surprised at an implementation-level mutex for database operations. I assume this is so we can share a document buffer across worker threads, but it effectively also constrains us to at most one mongo operation concurrently when we have multiple instances of the Mongo Output, even if those instances are in separate pipelines.

File: lib/logstash/outputs/mongodb.rb [hunk 2]
```diff
@@ -67,22 +70,32 @@ def register
...
+          # not using timestamp.to_bson
+          document["@timestamp"] = timestamp.to_json
+        else
+          @logger.warn("Cannot set MongoDB document `@timestamp` field because it does not exist in the event", :event => event)
+        end
       end
+
       if @generateId
-        document["_id"] = BSON::ObjectId.new(nil, event.timestamp)
+        document["_id"] = BSON::ObjectId.new
```
Comment (yaauie) [inline lib/logstash/outputs/mongodb.rb:94]: if we _do_ have a timestamp, it should still be used as the seed for the `BSON::ObjectId`.

File: lib/logstash/outputs/mongodb.rb [hunk 3]
```diff
@@ -46,19 +46,22 @@ class LogStash::Outputs::Mongodb < LogStash::Outputs::Base
...
     @db = conn.use(@database)
 
-    if @bulk_size > 1000
-      raise LogStash::ConfigurationError, "Bulk size must be lower than '1000', currently '#{@bulk_size}'"
-    end
+    @closed = Concurrent::AtomicBoolean.new(false)
     @documents = {}
-    Thread.new do
+
+    @bulk_thread = Thread.new(@bulk_interval) do |bulk_interval|
```
Comment (yaauie) [inline lib/logstash/outputs/mongodb.rb:61]: if `@bulk` is false, we should avoid creating the bulk thread.

File: lib/logstash/outputs/mongodb.rb [hunk 4]
```diff
@@ -67,22 +70,32 @@ def register
...
       end
+
       if @generateId
-        document["_id"] = BSON::ObjectId.new(nil, event.timestamp)
+        document["_id"] = BSON::ObjectId.new
       end
+
       if @bulk
         @@mutex.synchronize do
           collection = event.sprintf(@collection)
```
Comment (yaauie) [inline lib/logstash/outputs/mongodb.rb]: nitpick unrelated to your proposed changes: we should pull this sprintf out of the global mutex block to improve performance.

File: lib/logstash/outputs/mongodb.rb [hunk 5]
```diff
@@ -99,20 +112,24 @@ def receive(event)
...
         retry
       end
     end
-  end # def receive
-end # class LogStash::Outputs::Mongodb
+  end
+
+  def close
+    @closed.make_true
+    @bulk_thread.join
```
Comment (yaauie) [inline lib/logstash/outputs/mongodb.rb:132]: we may also want to send [`Thread#wakeup`](https://ruby-doc.org/core-2.3.0/Thread.html#method-i-wakeup) to our `@bulk_thread` to prevent it from sleeping off the remainder of its interval unnecessarily.

File: lib/logstash/outputs/mongodb.rb [hunk 6]
```diff
@@ -67,22 +70,32 @@ def register
             end
           end
         end
+
+        break if @closed.true?
```
Comment (yaauie) [inline lib/logstash/outputs/mongodb.rb]: nitpick: since this is at the tail end of the block passed to `Kernel#loop`, I'd prefer to use either [`until @closed.true? do` ... `end`] or [`while @closed.false? do` ... `end`].

**Review by yaauie — CHANGES_REQUESTED** [review]
ObjectId needs to be seeded from the timestamp if present.

Other nitpicks/suggestions inline.

File: lib/logstash/outputs/mongodb.rb (hunk 1 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb:65]: Yes, did not want to change that because it is out-of-scope and risks changing behaviours in ways it is difficult for me to track. If a refactor of this is eventually needed we can revisit.

File: lib/logstash/outputs/mongodb.rb (hunk 2 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb:94]: - when adding the specs this `BSON::ObjectId` was actually freezing.
- looking at the `BSON::ObjectId` doc, the parameter should be an array of bytes, which probably explain the above problem.
```
Parameters:
(Array) data (defaults to: nil) — should be an array of bytes. If you want to generate a standard MongoDB object id, leave this argument blank.
```

Furthermore
```
 If no parameter is given, an id corresponding to the ObjectId BSON data type will be created. This is a 12-byte value consisting of a 4-byte timestamp, a 3-byte machine id, a 2-byte process id, and a 3-byte counter.
```

Which should be good to satisfy the intent of the option.

File: lib/logstash/outputs/mongodb.rb (hunk 3 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb:61]: agree, but I wanted to minimize functional changes and figured this will anyway be revisited when refactoring the concurrency control code (and that thread has very minimal impact)

File: lib/logstash/outputs/mongodb.rb (hunk 4 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb]: sure - but same comment about the concurrency code.

File: lib/logstash/outputs/mongodb.rb (hunk 5 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb:132]: good idea.

File: lib/logstash/outputs/mongodb.rb (hunk 6 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb]: ok.

File: lib/logstash/outputs/mongodb.rb (hunk 2 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb:94]: I looked a bit more into the BSON code and there is a `BSON::ObjectId#from_time` method but there is a risk of creating non-unique IDs unless a `:unique => true` option is passed  and I don't really see the benefit of doing that vs a bare `BSON::ObjectId.new` which will be unique.

File: lib/logstash/outputs/mongodb.rb (hunk 5 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb:132]: done

File: lib/logstash/outputs/mongodb.rb (hunk 4 above)
Comment (colinsurprenant) [reply lib/logstash/outputs/mongodb.rb]: done.

**Comment by colinsurprenant** [comment]
Thanks for the review @yaauie !  I push some of the suggested changes. See comments for the other suggestions.

**Comment by colinsurprenant** [comment]
@yaauie let me know if you are good with my changes & comments to your review. Thanks.

**Comment by yaauie** [comment]
LGTM 🙌🏼
